CREATE DATABASE IF NOT EXISTS limbus;
USE limbus;

CREATE TABLE IF NOT EXISTS `Sinners` (
    `id` INT PRIMARY KEY,
    `Sinner_name` VARCHAR(255),
    `Source` VARCHAR(255),
    `Bday` VARCHAR(255),
    `Sin_id` INT,
    `Subtitle` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `EGO` (
    `id` INT PRIMARY KEY,
    `S_id` INT,
    `EGO_name` varchar(255),
    `Abno` VARCHAR(255),
    `Sin_id` INT
);

CREATE TABLE IF NOT EXISTS `Abno` (
    `id` INT PRIMARY KEY,
    `classification` VARCHAR(255),
    `Abno_name` VARCHAR(255),
    `risk` VARCHAR(255),
    `EGO` VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS `Sins` (
    `id` INT PRIMARY KEY,
    `Sin_name` VARCHAR(255),
    `status` VARCHAR(255)
);

insert into sins values
(1,"Wrath","burn"),
(2,"Lust","burn"),
(3,"Sloth","burn"),
(4,"Gluttony","burn"),
(5,"Gloom","burn"),
(6,"Pride","burn"),
(7,"Envy","burn");

insert into sinners values
(1,"Yi Sang","The Wing","January 1",3,"Ha Yung"),
(2,"Faust","Goethe's Faust","February 2",6,"WALPURGISNACHT"),
(3,"Don Quixote","The Ingenious Gentleman Don Quixote of La Mancha","March 3",2,"SUEÑO IMPOSIBLE"),
(4,"Ryōshū","Hell Screen","April 4",2,"森羅炎象"),
(5,"Meursault","The Stranger","May 5",6,"SOLEIL"),
(6,"Hong Lu","Dream of the Red Chamber","June 6",5,"太虛幻境"),
(7,"Heathcliff","Wuthering Heights","July 7",7,"REVENGE"),
(8,"Ishmael","Moby-Dick","August 8",5,"HEARSE"),
(9,"Rodion","Crime and Punishment","September 9",6,"РАСКО́Л"),
(11,"Sinclair","Demian: The Story of Emil Sinclair's Youth","November 11",4,"VOGEL"),
(12,"Outis","Odyssey","December 12",6,"ΟΥΤΙΣ"),
(13,"Gregor","The Metamorphosis","February 29",3,"UNGEZIEFER")
;
insert into sinners (id,Sinner_name,Source,Bday,Subtitle)values
(10,"Dante","Dante's Inferno","October 10","DURANTE")
;

insert into abno values
("1","O-02-04-13","???","","Feral Mane"),
("2","O-02-11-10","???","","Coil"),
("3","T-06-27","1.76 MHz","TETH","Noise"),
("4","?-??-??-??","All-Around Cleaner","","???"),
("5","O-02-10-11","Alleyway Watchdog","HE-03","Telepole"),
("6","T-04-53","Alriune","WAW","Faint Aroma"),
("7","O-02-21-11","Ambling Pearl","WAW-05","Effervescent Corrosion"),
("8","O-01-20-07","Ardor Blossom Moth","WAW-05","Ardor Blossom Star"),
("9","F-02-10-18","Baba Yaga","TETH-05","Rime Shank"),
("10","?-??-??-??","Basilisoup","","Lifetime Stew"),
("11","O-02-40","Big Bird","WAW","Lamp"),
("12","T-01-23-04","Blubbering Toad","ZAYIN-01","Cavernous Wailing"),
("13","?-??-??-??","Blue-ish Star","","???"),
("14","M-01-11-07","Brazen Bull","TETH-03","Capote"),
("15","?-??-??-??","Broken Wings","","???"),
("16","?-??-??-??","Burning Duchess","","Indicant's Trial"),
("17","0-03-14-03","Butterfly of Entangled Lives [羅生蝶]","WAW-06","Great Trichiliocosm [三千大世界]"),
("18","?-??-??-??","Centaur","","???"),
("19","?-??-??-??","Centipede Apostle","","Hundred-Footed Death Maggot [蝍蛆殺]"),
("20","?-??-??-??","Chattering Teeth","","???"),
("21","?-??-??-??","Children in the Flask","","???"),
("22","?-??-??-??","Clockwork-Time-Roly-Poly","","Asymmetrical Inertia"),
("23","?-??-??-??","Cozy Bed","","Christmas Nightmare"),
("24","?-??-??-??","Cyclops","","???"),
("25","F-01-16-13","Der Fluchschütze","HE-04","Fell Bullet"),
("26","F-01-69","Der Freischütz","HE","Magic Bullet"),
("27","?-??-??-??","Dimensional Orbit Stabilizer","","???"),
("28","?-??-??-??","Dimensional Oxidation Variant","","???"),
("29","O-03-88","Dimensional Refraction Variant","WAW","Diffraction"),
("30","M-04-04-05","Doomsday Calendar","HE-08","Impending Day"),
("31","T-02-21-06","Dream-Devouring Siltcurrent","WAW-05","Blind Obsession"),
("32","F-01-20-08","Dreaming Electric Sheep","HE-05","Electric Screaming"),
("33","O-04-20-11","Drenched Gossypium","TETH-03","???"),
("34","T-02-11-03","Drifting Fox","HE-04","Sunshower"),
("35","?-??-??-??","Drunkard","","???"),
("36","F-04-03-04","Ebony Queen's Apple","WAW-04","Ebony Stem"),
("37","?-??-??-??","Explorer on a Bereaved Road","","???"),
("38","F-04-21-03","Faelantern","TETH-03","Lantern"),
("39","F-04-20-83","Fairy Festival","ZAYIN-04","Wingbeat"),
("40","F-01-11-12","Fairy Gentleman","TETH-03","Sloshing"),
("41","F-01-11-15","Fairy-Long-Legs","TETH-03","Sticking"),
("42","?-??-??-??","Forsaken Employee","","???"),
("43","T-01-54","Forsaken Murderer","TETH","Regret"),
("44","F-04-16-04","Four-hundred Roses","WAW-05","Yearning-Mircalla"),
("45","?-??-??-??","Funeral of a Dying Butterfly","","???"),
("46","T-01-68","Funeral of the Dead Butterflies","HE","Solemn Lament"),
("47","O-02-04-06","Golden Apple","HE-02","Legerdemain"),
("48","?-??-??-??","Golden Grip","","???"),
("49","?-??-??-??","Handshake of Handshakes","","???"),
("50","T-04-10-06","Have You Become Strong","???","Screwloose Wallop"),
("51","O-02-11-26","Headless Ichthys","HE-04","Fluid Sac"),
("52","?-??-??-??","Heavenly Commander's Scribe","","???"),
("53","?-??-??-??","Heavenly Executor's Scribe","","Pursuance"),
("54","?-??-??-??","Highway Devotee","","???"),
("55","?-??-??-??","Hole-in-the-Man","","???"),
("56","T-04-16-02","Hurting Teddy Bear","TETH-03","Hex Nail"),
("57","?-??-??-??","Hydra","","???"),
("58","O-05-20-02","kqe-1j-23","HE-04","Move-in Reg."),
("59","O-04-84","Meat Lantern","TETH","Lantern"),
("60","?-??-??-??","Monkey Tree","","???"),
("61","M-04-04-04","My Form Empties","WAW-08","Ya Śūnyatā Tad Rūpam"),
("62","O-06-20","Nothing There","ALEPH","Mimicry"),
("63","?-??-??-??","Nymph","","???"),
("64","O-01-12","Old Lady","TETH","Solitude"),
("65","O-03-03","One Sin and Hundreds of Good Deeds","ZAYIN","Penitence"),
("66","F-05-52","Opened Can of WellCheers","ZAYIN","Soda"),
("67","?-??-??-??","Overdue Assignments","","???"),
("68","?-??-??-??","Pagoda Veneration","","Wishing Cairn"),
("69","?-??-??-??","Paper Chairman","","???"),
("70","F-04-10-13","Pink Shoes","???","Roseate Desire"),
("71","O-02-20-05","Portrait of a Certain Day","TETH-04","Bygone Days"),
("72","O-02-56","Punishing Bird","TETH","Beak"),
("73","T-04-50","Queen Bee","WAW","Hornet"),
("74","?-??-??-??","Recurring Faith and Promise","","???"),
("75","O-04-08","Red Shoes","HE","Sanguine Desire"),
("76","?-??-??-??","Resident of Metropolaris","","???"),
("77","?-??-??-??","Rising Ashes","","???"),
("78","F-01-16-10","Rose Hunter","HE-03","Lasso"),
("79","?-??-??-??","Sandolph","","Holiday"),
("80","O-05-76","Schadenfreude","HE","Gaze"),
("81","F-01-02","Scorched Girl","TETH","4th Match Flame"),
("82","T-02-11-04","Shock Centipede","HE-03","AEDD"),
("83","O-04-21-22","Sign of Roses","WAW-06","Garden of Thorns"),
("84","O-05-30","Singing Machine","HE","Harmony"),
("85","T-03-21-09","Skin Prophet","TETH-04","9:2"),
("86","T-03-16-15","Sleeping Bag of a Bygone Day","TETH-03","Thoracalgia"),
("87","?-??-??-??","Sleepyhead","","???"),
("88","?-??-??-??","Smokey Old Man","","???"),
("89","T-04-11-20","So That No One Will Cry","TETH-02","Red Sheet"),
("90","T-02-43","Spider Bud","TETH","Red Eyes"),
("91","?-??-??-??","Spider of Marriage","","???"),
("92","T-03-20-04","Spiral of Contempt","WAW-06","Contempt, Awe"),
("93","?-??-??-??","Star Luminary","","???"),
("94","O-05-21-16","Steam Transport Machine","HE-04","Crushbound Past"),
("95","?-??-??-??","Stuck in Heaven","","???"),
("96","?-??-??-??","Sunset Wayfarer","","Into the Sunset"),
("97","?-??-??-??","The 4th Front of the Smoke War","","???"),
("98","O-01-20-12","The King in Binds","WAW-07","Binds"),
("99","O-01-73","The Knight of Despair","WAW","The Sword Sharpened with Tears"),
("100","O-01-04","The Queen of Hatred","WAW","In the Name of Love and Hate"),
("101","?-??-??-??","Time Duck","","Everlasting"),
("102","?-??-??-??","Tomb of Bone","","???"),
("103","?-??-??-??","Tomorrow's Expression","","???"),
("104","?-??-??-??","Wailing Coffin","","???"),
("105","?-??-??-??","Wandering Mind","","???"),
("106","T-02-21-07","Wayward Passenger","HE-04","Dimension Shredder"),
("107","T-01-14-11","Will You Play?","ZAYIN-04","I'll Go fer Scissors. How 'Bout You?"),
("108","F-02-14-23","Yinglong","WAW-05","Tears of the Tarnished Blood [汚血泣涙]")
;

insert into EGO values
(1,1,"Crow's Eye View ","Yi Sang",3),
(2,1,"Bygone Days ","Portrait of a Certain Day",5),
(3,1,"4th Match Flame ","Scorched Girl",1),
(4,1,"Wishing Cairn ","Pagoda Veneration",3),
(5,1,"Dimension Shredder ","Wayward Passenger",6),
(6,1,"Fell Bullet ","Der Fluchschütze",6),
(7,1,"Sunshower","Drifting Fox",3),
(8,1,"Great Trichiliocosm 三千大世界","Butterfly of Entangled Lives [羅生蝶]",1),
(9,2,"Representation Emitter ","Faust",6),
(10,2,"Hex Nail ","Hurting Teddy Bear",7),
(11,2,"9:2","Skin Prophet",2),
(12,2,"Lasso ","Rose Hunter",4),
(13,2,"Fluid Sac ","Headless Ichthys",5),
(14,2,"Telepole ","Alleyway Watchdog",7),
(15,2,"Thoracalgia ","Sleeping Bag of a Bygone Day",6),
(16,2,"Command - Meltdown ","Kal'tsit",4),
(17,2,"Ardor Blossom Star ","Ardor Blossom Moth",1),
(18,2,"Everlasting ","Time Duck",3),
(19,3,"La Sangre de Sancho","Don Quixote",2),
(20,3,"Lifetime Stew","Basilisoup",2),
(21,3,"Wishing Cairn","Pagoda Veneration",3),
(22,3,"Electric Screaming","Dreaming Electric Sheep",7),
(23,3,"Fluid Sac","Headless Ichthys",5),
(24,3,"Telepole","Alleyway Watchdog",7),
(25,3,"Red Sheet","So That No One Will Cry",4),
(26,3,"Yearning-Mircalla","Four-hundred Roses",2),
(27,3,"In the Name of Love and Hate","The Queen of Hatred",7),
(28,4,"Forest for the Flames","Ryōshū",2),
(29,4,"Soda","Wellcheers",5),
(30,4,"Red Eyes","Spider Bud",2),
(31,4,"Blind Obsession","Dream-Devouring Siltcurrent",6),
(32,4,"4th Match Flame","Scorched Girl",1),
(33,4,"Red Eyes (Open)","Spider Bud",7),
(34,4,"Thoracalgia","Sleeping Bag of a Bygone Day",6),
(35,4,"Contempt, Awe","Spiral of Contempt",2),
(36,4,"Great Trichiliocosm 三千大世界","Butterfly of Entangled Lives [羅生蝶]",1),
(37,5,"Chains of Others","Meursault",6),
(38,5,"Screwloose Wallop","You Want To Get Beat? Hurtily?",7),
(39,5,"Regret","Forsaken Murderer",1),
(40,5,"Electric Screaming","Dreaming Electric Sheep",7),
(41,5,"Pursuance","Heavenly Executor's Scribe",3),
(42,5,"Capote","Brazen Bull",1),
(43,5,"Yearning-Mircalla","Four-hundred Roses",2),
(44,5,"Crushbound Past","Steam Transport Machine",3),
(45,6,"Land of Illusion","Hong Lu",5),
(46,6,"Roseate Desire","Pink Shoes",2),
(47,6,"Soda","Wellcheers",7),
(48,6,"Cavernous Wailing ","Blubbering Toad",5),
(49,6,"Lasso ","Rose Hunter",4),
(50,6,"Dimension Shredder","Wayward Passenger",6),
(51,6,"Effervescent Corrosion","Ambling Pearl",4),
(52,6,"To Remain Oneself 宁作吾 ","Ling",6),
(53,6,"Tears of the Tarnished Blood 汚血泣淚","Yinglong",4),
(54,7,"Bodysack","Heathcliff",7),
(55,7,"Holiday","Sandolph",4),
(56,7,"AEDD","Shock Centipede",5),
(57,7,"Fell Bullet","Der Fluchschütze",6),
(58,7,"Move-in Reg.","kqe-1j-23",7),
(59,7,"Telepole","Alleyway Watchdog",7),
(60,7,"Ya Śūnyatā Tad Rūpam","My Form Empties",2),
(61,7,"Asymmetrical Inertia ","Clockwork-Time-Roly-Poly",3),
(62,7,"Binds","The King in Binds",5),
(63,8,"Snagharpoon","Ishmael",5),
(64,8,"Hundred-Footed Death Maggot 蝍蛆殺 ","Centipede Apostle",5),
(65,8,"Roseate Desire ","Pink Shoes",2),
(66,8,"Capote","Brazen Bull",1),
(67,8,"Bygone Days ","Portrait of a Certain Day",5),
(68,8,"Ardor Blossom Star","Ardor Blossom Moth",1),
(69,8,"Wingbeat ","Fairy Festival",4),
(70,8,"Christmas Nightmare","Cozy Bed",3),
(71,8,"Tidal Elegy","Skadi",5),
(72,8,"Blind Obsession","Dream-Devouring Siltcurrent",6),
(73,9,"What is Cast","Rodion",6),
(74,9,"Into the Sunset","Sunset Wayfarer",2),
(75,9,"Rime Shank","Baba Yaga",5),
(76,9,"Effervescent Corrosion","Ambling Pearl",4),
(77,9,"4th Match Flame ","Scorched Girl",1),
(78,9,"Pursuance","Heavenly Executor's Scribe",3),
(79,9,"Hex Nail","Hurting Teddy Bear",7),
(80,9,"Sanguine Desire","The Red Shoes",2),
(81,9,"Indicant's Trial","Burning Duchess",1),
(82,11,"Branch of Knowledge ","Sinclair",4),
(83,11,"Cavernous Wailing ","Blubbering Toad",5),
(84,11,"Impending Day","Doomsday Calendar",1),
(85,11,"Lifetime Stew ","Basilisoup",2),
(86,11,"Hex Nail ","Hurting Teddy Bear",7),
(87,11,"Lantern ","Faelantern",4),
(88,11,"9:2","Skin Prophet",2),
(89,11,"Harmony","Singing Machine",1),
(90,11,"Tears of the Tarnished Blood 汚血泣淚 ","Yinglong",4),
(91,12,"To Páthos Máthos","Outis",6),
(92,12,"I'll Go fer Scissors. How 'Bout You?","Will You Play?",7),
(93,12,"Ya Śūnyatā Tad Rūpam ","My Form Empties",2),
(94,12,"Sunshower","Drifting Fox",4),
(95,12,"Ebony Stem","Ebony Queen's Apple",4),
(96,12,"Holiday","Sandolph",1),
(97,12,"Dimension Shredder","Wayward Passenger",7),
(98,12,"Magic Bullet ","Der Freischütz",6),
(99,12,"Binds ","The King in Binds",6),
(100,13,"Suddenly, One Day ","Gregor",3),
(101,13,"Legerdemain","Golden Apple",4),
(102,13,"Lantern","Faelantern",4),
(103,13,"Bygone Days","Portrait of a Certain Day",5),
(104,13,"AEDD","Shock Centipede",5),
(105,13,"Solemn Lament","Funeral of the Dead Butterflies",5),
(106,13,"Christmas Nightmare","Cozy Bed",3),
(107,13,"Garden of Thorns","Sign of Roses",2),
(108,13,"Unbrilliant Glory ","Młynar",3)
;
